### ISSUE TITLE
Always display the resulting dataset in display, datasets and query exercises

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#11]
Currently, the resulting dataset is only displayed if there are comparison failures in `query` tests, and never in `display` tests. 

## Test

```yaml
- type: query
  seed: | # Opcional
    INSERT INTO foo VALUES ('dato 1');
    INSERT INTO foo VALUES ('dato 2');
  expected: SELECT * FROM foo;
``` 

## Extra Code

```sql
create table foo (dato varchar);
```

## Solution

```sql
select * from foo;
```

## Output

![image](https://user-images.githubusercontent.com/677436/34323483-07108346-e82a-11e7-849e-38c597ac6370.png)

## Problem

You don't see the query output.
