### ISSUE TITLE
Expected and actual results are swapped

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#12]
Currently, the resulting datasets are swapped in a `query` test

# Examples

### Test

```yaml
- type: query
  seed: | # Opcional
    INSERT INTO foo VALUES ('dato 1');
    INSERT INTO foo VALUES ('dato 2');
  expected: SELECT * FROM foo;
``` 

### Extra Code

```sql
create table foo (dato varchar);
```

### Solution

```sql
select 1 from foo;
```

### Output

![image](https://user-images.githubusercontent.com/677436/34323487-3500df8a-e82a-11e7-83fd-ce7ac1e8cb7a.png)

### Solution

```sql
select 1 as dato from foo;
```
### Output

![image](https://user-images.githubusercontent.com/677436/34323493-53f6666c-e82a-11e7-86c3-44c5da196750.png)

### Test

```yaml
- type: query
  seed: | # Opcional
    INSERT INTO foo VALUES ('dato 1');
    INSERT INTO foo VALUES ('dato 2');
  expected: SELECT * FROM foo;
- type: query
  seed: | # Opcional
    INSERT INTO foo VALUES ('dato 2');
    INSERT INTO foo VALUES ('dato 3');
  expected: SELECT * FROM foo;
```

### Solution

```sql
select 1 as dato from foo;
```

### Output

![image](https://user-images.githubusercontent.com/677436/34323495-8640b384-e82a-11e7-8e01-2443e84063bc.png)
