### ISSUE TITLE
Final query should be displayed on results on exercise type `final_dataset`

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#13]
For example: 

## Test

```yaml
- type: final_dataset
  final: select dato from foo;
  expected: |
    descrip
    dato 1
    dato 2
```

## Extra Code

```sql
create table foo (dato varchar);
```

## Solution 

```sql
INSERT INTO foo values ('dato 1');
```

## Output 

![image](https://user-images.githubusercontent.com/677436/34323574-967dadac-e82e-11e7-9036-3e042cad1aa5.png)

## Problem

It is not obvious why those results sets where expected of obtained, since the user was asked to enter an `insert`/`update`/`delete` statement. It would be nice to see something like this: 

![image](https://user-images.githubusercontent.com/677436/34323594-6c848c2c-e82f-11e7-80ab-bdcb8c8be1c5.png)
