### ISSUE TITLE
Reduce metadata test template

### ISSUE THREAD

**Issue by laendoor** [mumuki/mumuki-sqlite-runner#15]
Test template is too long and annoying. I think we can reduce it by providing only one type.

Alternatives:

* Random
* Fixed on `datasets`:
```yaml
# https://github.com/mumuki/mumuki-sqlite-runner/wiki
type: datasets     # final_dataset, query, display
final: SELECT * FROM ...
expected: |
  id|name
  1|foo
  2|bar
```

For more details I wrote the [wiki](https://github.com/mumuki/mumuki-sqlite-runner/wiki)

What do you think?
