### ISSUE TITLE
Flag para mostrar/ocultar el diff

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-sqlite-runner#22]
Acá charlando con @fedescarpa y @NadiaFinzi pensamos que más allá de la cuestión de fondo (cómo mostrar el diff), el diff en los primeros ejercicios (en los que explicamos qué es una tabla, que es una fila, etc) confunde, más allá de su formato.

Por eso les propongo que haya un flag  `hide_tables_diff` que permita ocultarlo, por ejercicio, que sea parte YAML del test, similar a los flags de ocultar  el tablero de gobstones (https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/metadata_hook.rb#L39).

Related to https://github.com/mumuki/mumuki-sqlite-runner/issues/20

**Comment by NadiaFinzi** [comment]
Estoy pensando que no sé si es necesario en cada ejercicio tener que decir si ocultar o no el diff. 

Concretamente, solo los ejercicios con tipo "display" carecen de comparación, por lo que prescindirían del diff.

**Comment by flbulgarelli** [comment]
De acuerdo. Solo valdría para aquellos en los que se necesita.

**Comment by flbulgarelli** [comment]
Algo así: 

```yaml
hide_tables_diff: true # por default debería ser false
- type: query
  seed: | 
    INSERT INTO table VALUES ('dato 1');
    INSERT INTO table VALUES ('dato 2');
  expected: SELECT * FROM table;
```
